---
name: Malicious unicode scanning
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  unicop:
    # Unicop is not platform specific in any way. The results should be identical
    # for any input source code, no matter what platform it runs on.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup default stable
          rustup update stable

      - name: Install unicop
        run: |
          cargo install --locked unicop
          unicop --version

      - name: Check for unwanted unicode
        run: unicop --verbose .
